### ISSUE TITLE
Embeded Media not Floating Properly

### ISSUE THREAD

**Issue by Bosterm** [alexdryden/default#70]
Because I surrounded all blocks in divs, the media is no longer floating around text.

**Comment by Bosterm** [comment]
Okay never mind, it's actually because of the clear-fix solution that this is happening. There is an alternative solution though, I just inserted a `<div class="clearfix"></div>` at the end of the main-content-container so that it always happens. I'll just need you to remove the code that adds that div after each media, since I don't want to mess up how you did it.

This is in the i70_uiuc branch.

**Comment by alexdryden** [comment]
@Bosterm I'm trying to remember, was the previous clearfix solution from #26 ?

**Comment by alexdryden** [comment]
Oh--gotcha. It was from #46. Okay, removed that div and pushed the changes into i70_uiuc
